export const HIGHLIGHT_LANGUAGE_IDS = [
  'arduino',
  'bash',
  'c',
  'cpp',
  'csharp',
  'css',
  'diff',
  'go',
  'graphql',
  'ini',
  'java',
  'javascript',
  'json',
  'kotlin',
  'less',
  'lua',
  'makefile',
  'markdown',
  'objectivec',
  'perl',
  'php',
  'php-template',
  'plaintext',
  'python',
  'python-repl',
  'r',
  'ruby',
  'rust',
  'scss',
  'shell',
  'sql',
  'swift',
  'typescript',
  'vbnet',
  'wasm',
  'xml',
  'yaml',
] as const;

export type HighlightLanguageId = (typeof HIGHLIGHT_LANGUAGE_IDS)[number];

const ALIAS_TO_CANONICAL: Record<string, HighlightLanguageId> = {
  arduino: 'arduino',
  ino: 'arduino',
  bash: 'bash',
  sh: 'bash',
  zsh: 'bash',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  'c++': 'cpp',
  'h++': 'cpp',
  hpp: 'cpp',
  hh: 'cpp',
  hxx: 'cpp',
  cxx: 'cpp',
  csharp: 'csharp',
  cs: 'csharp',
  'c#': 'csharp',
  css: 'css',
  diff: 'diff',
  patch: 'diff',
  go: 'go',
  golang: 'go',
  graphql: 'graphql',
  gql: 'graphql',
  ini: 'ini',
  toml: 'ini',
  java: 'java',
  jsp: 'java',
  javascript: 'javascript',
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  kotlin: 'kotlin',
  kt: 'kotlin',
  kts: 'kotlin',
  less: 'less',
  lua: 'lua',
  pluto: 'lua',
  makefile: 'makefile',
  mk: 'makefile',
  mak: 'makefile',
  make: 'makefile',
  markdown: 'markdown',
  md: 'markdown',
  mkdown: 'markdown',
  mkd: 'markdown',
  objectivec: 'objectivec',
  mm: 'objectivec',
  objc: 'objectivec',
  'obj-c': 'objectivec',
  'obj-c++': 'objectivec',
  'objective-c++': 'objectivec',
  perl: 'perl',
  pl: 'perl',
  pm: 'perl',
  php: 'php',
  'php-template': 'php-template',
  plaintext: 'plaintext',
  text: 'plaintext',
  txt: 'plaintext',
  python: 'python',
  py: 'python',
  gyp: 'python',
  ipython: 'python',
  'python-repl': 'python-repl',
  pycon: 'python-repl',
  r: 'r',
  ruby: 'ruby',
  rb: 'ruby',
  gemspec: 'ruby',
  podspec: 'ruby',
  thor: 'ruby',
  irb: 'ruby',
  rust: 'rust',
  rs: 'rust',
  scss: 'scss',
  shell: 'shell',
  console: 'shell',
  shellsession: 'shell',
  sql: 'sql',
  swift: 'swift',
  typescript: 'typescript',
  ts: 'typescript',
  tsx: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  vbnet: 'vbnet',
  vb: 'vbnet',
  wasm: 'wasm',
  xml: 'xml',
  html: 'xml',
  xhtml: 'xml',
  rss: 'xml',
  atom: 'xml',
  xjb: 'xml',
  xsd: 'xml',
  xsl: 'xml',
  plist: 'xml',
  wsf: 'xml',
  svg: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
};

export const resolveHighlightLanguage = (
  infoString: string,
): HighlightLanguageId | null => {
  const normalized = infoString.trim().toLowerCase();

  if (normalized.length === 0) {
    return null;
  }

  const token = normalized.split(/[\s{]/)[0] ?? '';

  if (token.length === 0) {
    return null;
  }

  return ALIAS_TO_CANONICAL[token] ?? null;
};
